# Generated by Django 5.0.1 on 2024-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Registered', 'Registered'), ('Resolved', 'Resolved')], default='Pending', max_length=50),
        ),
    ]
